apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-job
  namespace: platform
spec:
  schedule: "0 2 * * *"

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          containers:
            - name: cleanup
              image: platform/platform-core:latest

              command:
                - node
                - scripts/cleanup.js