apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: platform

type: Opaque

stringData:
  POSTGRES_USER: platform
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: platform