CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";

CREATE SCHEMA IF NOT EXISTS platform;
CREATE SCHEMA IF NOT EXISTS observability;
CREATE SCHEMA IF NOT EXISTS governance;
CREATE SCHEMA IF NOT EXISTS audit;

CREATE ROLE platform_app LOGIN;
CREATE ROLE readonly LOGIN;

GRANT USAGE ON SCHEMA platform TO platform_app;
GRANT USAGE ON SCHEMA observability TO platform_app;

ALTER DATABASE postgres SET timezone TO 'UTC';