bind 0.0.0.0
protected-mode yes
port 6379

tcp-backlog 511
timeout 0
tcp-keepalive 300

daemonize no
supervised systemd

databases 32

maxmemory 8gb
maxmemory-policy allkeys-lru

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

rdbcompression yes
rdbchecksum yes

stop-writes-on-bgsave-error yes

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes

io-threads 4
io-threads-do-reads yes

aclfile /etc/redis/acl.conf

loglevel notice
logfile ""

latency-monitor-threshold 100

notify-keyspace-events Ex

client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 64mb 16mb 60