apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: agent-service-dr
  namespace: platform
spec:
  host: agent-service.platform.svc.cluster.local

  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

    loadBalancer:
      simple: ROUND_ROBIN

    connectionPool:
      tcp:
        maxConnections: 1000