apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: platform-pods
  namespace: observability

spec:
  selector:
    matchLabels:
      monitoring: enabled

  namespaceSelector:
    any: true

  podMetricsEndpoints:
    - port: metrics
      interval: 15s