apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-services
  namespace: observability

spec:
  selector:
    matchLabels:
      monitoring: enabled

  namespaceSelector:
    any: true

  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s