apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway-vs
  namespace: platform
spec:
  gateways:
    - public-gateway

  hosts:
    - api.ai-saas.com

  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: api-gateway.platform.svc.cluster.local
            port:
              number: 8080
      retries:
        attempts: 3
        perTryTimeout: 5s
      timeout: 30s