primary_conninfo = '
host=postgres-primary
port=5432
user=replicator
password=${REPLICATION_PASSWORD}
application_name=postgres-replica
'

primary_slot_name = replica_slot_01

hot_standby = on