apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: distributed-tracing
  namespace: platform
spec:
  tracing:
    - providers:
        - name: tempo

      randomSamplingPercentage: 100