apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: rollback-workflow
  namespace: argo
spec:
  entrypoint: rollback

  templates:
    - name: rollback
      container:
        image: bitnami/kubectl:latest
        command:
          - kubectl
        args:
          - rollout
          - undo
          - deployment/platform-core